// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Encryption Keys",
  description: "Symmetric keys a WASI module seals data with and never sees, derived in the TEE keystore like signing keys: the manifest encryption_keys declaration, the…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
