// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "NEAR Integration",
  description: "Calling `request_execution` from a NEAR contract: arguments, callback shape, gas and payment, FastFS workflow, attestation of the returned result",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
