// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Projects",
  description: "Project IDs, how a WASM binary is bound to a project, project environment variables, version management, storage security model",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
