// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Workers",
  description: "The live TEE fleet executing OutLayer jobs — every worker's Intel TDX attestation is independently verifiable.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
