// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Building OutLayer App",
  description: "Writing the agent itself: WASI Preview 1 vs. Preview 2, supported languages, host functions, resource limits, local testing, common pitfalls",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
