// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "TEE Attestation",
  description: "What a worker signature proves: worker registration, post-quantum keys, per-execution attestation, data freshness, verification process",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
