// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Stats",
  description: "Platform-wide metrics: executions, success rate, custody activity and live pricing limits, refreshed every 30 seconds.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
