// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Binding API reference",
  description: "The calls a bound-account integration makes: which of the two account identities each endpoint is about (everything under /binding/ is the asset account…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
