// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Secrets",
  description: "Encrypted secrets only your code inside the enclave can read: create them, bind to projects and control access conditions.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
