// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "MPC Vaults",
  description: "Per-customer sovereign vaults: creation, vault-scoped secrets and wallets, recovery procedures, end-user verification, threat model",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
