// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Getting Started",
  description: "What OutLayer is, the two integration modes (NEAR contract callback vs. HTTPS API), and a first working agent",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
