// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Earnings",
  description: "How developers earn from blockchain and HTTPS calls, checking attached payment inside WASM, viewing and withdrawing balances",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
