// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Vaults",
  description: "Deploy a sovereign MPC vault bound to your NEAR account and keep custody of secrets and wallets under your own contract.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
