// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Secrets",
  description: "Encrypted secrets decrypted only inside the enclave: binding types, access control, storage costs, confidential key derivation (CKD), DAO-governed keystore",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
