// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "HTTPS API",
  description: "Request and response format for `POST /call/{project_owner}/{project_name}`: base URLs per network, headers, body, environment variables, error codes",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
