// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Projects",
  description: "Create OutLayer projects, manage versions and per-project secrets, and keep persistent storage across code updates.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
