// Single source of truth for the docs sidebar: groups → pages → in-page sections.
// Consumed by app/docs/layout.tsx (sidebar + anchor nav). scripts/llms-manifest.mjs
// lists the same pages for llms.txt — keep it aligned when adding a page here.
// Plain .mjs so both Next and node scripts can import it.

export const DOCS_NAV = [
  {
    group: null,
    pages: [
      {
        href: '/docs/getting-started',
        label: 'Getting Started',
        sections: [
          { id: 'what-is-outlayer', title: 'Overview' },
          { id: 'two-modes', title: 'Integration Modes' },
          { id: 'quick-start', title: 'Quick Start' },
          { id: 'secrets', title: 'Features' },
        ],
      },
      {
        href: '/docs/examples',
        label: 'Example Projects',
        sections: [
          { id: 'random-ark', title: 'Random Number' },
          { id: 'vrf-ark', title: 'VRF (Verifiable Random)' },
          { id: 'echo-ark', title: 'Echo' },
          { id: 'ai-ark', title: 'AI Integration' },
          { id: 'weather-ark', title: 'Weather Oracle' },
          { id: 'oracle-ark', title: 'Price Oracle' },
          { id: 'ethereum-api', title: 'Ethereum API' },
          { id: 'eth-proof', title: 'Ethereum State Proof' },
          { id: 'botfather-ark', title: 'Bot Father' },
          { id: 'intents-ark', title: 'NEAR Intents swap' },
          { id: 'private-dao-ark', title: 'Private DAO Voting' },
          { id: 'captcha-ark', title: '2FA Verification' },
          { id: 'near-email', title: 'NEAR Email' },
        ],
      },
    ],
  },
  {
    group: 'Guides',
    pages: [
      {
        href: '/docs/near-integration',
        label: 'NEAR Integration',
        sections: [
          { id: 'request-execution', title: 'Method: request_execution' },
          { id: 'callback', title: 'Callback Response' },
          { id: 'example', title: 'Example Contract Call' },
          { id: 'pricing-payment', title: 'Pricing & Payment' },
          { id: 'performance', title: 'Performance Tips' },
          { id: 'fastfs-workflow', title: 'FastFS Workflow' },
          { id: 'tee-attestation', title: 'TEE Attestation' },
        ],
      },
      {
        href: '/docs/web2-integration',
        label: 'Web2 Integration',
        sections: [
          { id: 'why-web2', title: 'Why Web2 Integration?' },
          { id: 'quick-start', title: 'Quick Start' },
          { id: 'tee-attestation', title: 'TEE Attestation' },
          { id: 'payments', title: 'Payments & Monetization' },
          { id: 'env-vars', title: 'Environment Variables' },
          { id: 'api-reference', title: 'API Reference' },
          { id: 'code-examples', title: 'Code Examples' },
          { id: 'capabilities', title: 'Project Capabilities' },
        ],
      },
      {
        href: '/docs/wasi',
        label: 'Building OutLayer App',
        sections: [
          { id: 'what-is-wasi', title: 'What is WASI?' },
          { id: 'supported-languages', title: 'Supported Languages' },
          { id: 'wasi-preview', title: 'WASI Preview 1 vs Preview 2' },
          { id: 'wasi-interface', title: 'WASI Interface' },
          { id: 'host-functions', title: 'Host Functions (Advanced)' },
          { id: 'critical-requirements', title: 'Critical Requirements' },
          { id: 'working-examples', title: 'Working Examples' },
          { id: 'resource-considerations', title: 'Resource Considerations' },
          { id: 'testing-locally', title: 'Testing Locally' },
          { id: 'common-pitfalls', title: 'Common Pitfalls' },
          { id: 'next-steps', title: 'Next Steps' },
        ],
      },
      {
        href: '/docs/dev-guide',
        label: 'Tutorial: First App',
        sections: [
          { id: 'problem', title: 'The Problem' },
          { id: 'step-1', title: 'Step 1: Write WASI Code' },
          { id: 'step-2', title: 'Step 2: Push to GitHub' },
          { id: 'step-3', title: 'Step 3: Test on Testnet' },
          { id: 'step-4', title: 'Step 4: Integrate in Contract' },
        ],
      },
    ],
  },
  {
    group: 'OutLayer Features',
    pages: [
      {
        href: '/docs/agent-custody',
        label: 'Agent Custody',
        sections: [
          { id: 'how-it-works', title: 'How It Works' },
          { id: 'agent-id', title: 'Agent ID' },
          { id: 'multi-chain', title: 'Multi-Chain Support' },
          { id: 'policy-engine', title: 'Policy Engine' },
          { id: 'multisig', title: 'Multisig Approval' },
          { id: 'quick-start', title: 'Quick Start' },
          { id: 'api-reference', title: 'API Reference' },
          { id: 'confidential-intents', title: 'Confidential Intents' },
          { id: 'sign-message', title: 'Sign Message (NEP-413)' },
          { id: 'security', title: 'Security Model' },
          { id: 'ai-skill', title: 'AI Agent Skill File' },
          { id: 'cli-integration', title: 'CLI Integration' },
          { id: 'comparison', title: 'Comparison' },
          { id: 'dashboard', title: 'Dashboard' },
        ],
      },
      {
        href: '/docs/vaults',
        label: 'MPC Vaults',
        sections: [
          { id: 'overview', title: 'Overview' },
          { id: 'create', title: 'Creating a vault' },
          { id: 'secrets', title: 'Vault for secrets' },
          { id: 'custody', title: 'Vault for wallets' },
          { id: 'recovery', title: 'Recovery procedures' },
          { id: 'threat-model', title: 'For end-users' },
          { id: 'verify', title: 'End-user verification' },
          { id: 'ops', title: 'Operational considerations' },
        ],
      },
      {
        href: '/docs/payment-checks',
        label: 'Payment Checks',
        sections: [
          { id: 'how-it-works', title: 'How It Works' },
          { id: 'mechanism', title: 'Transfer Mechanism' },
          { id: 'key-derivation', title: 'Key Derivation' },
          { id: 'use-cases', title: 'Use Cases' },
          { id: 'quick-start', title: 'Quick Start' },
          { id: 'api-reference', title: 'API Reference' },
          { id: 'lifecycle', title: 'Check Lifecycle' },
          { id: 'security', title: 'Security Model' },
          { id: 'comparison', title: 'Comparison' },
        ],
      },
      {
        href: '/docs/secrets',
        label: 'Secrets',
        sections: [
          { id: 'what-are-secrets', title: 'What are Secrets?' },
          { id: 'creating-secrets', title: 'Creating Secrets' },
          { id: 'secrets-binding', title: 'Secrets Binding Types' },
          { id: 'project-binding', title: 'Project Binding' },
          { id: 'access-control', title: 'Access Control' },
          { id: 'using-secrets', title: 'Using Secrets in Code' },
          { id: 'storage-costs', title: 'Storage Costs' },
          { id: 'security-model', title: 'Security Model' },
          { id: 'confidential-key-derivation', title: 'Confidential Key Derivation (CKD)' },
          { id: 'dao-governance', title: 'DAO Governance & Keystore' },
          { id: 'ckd-faq', title: 'CKD & MPC FAQ' },
        ],
      },
      {
        href: '/docs/projects',
        label: 'Projects',
        sections: [
          { id: 'what-are-projects', title: 'What are Projects?' },
          { id: 'project-id', title: 'Project ID Format' },
          { id: 'creating-project', title: 'Creating a Project' },
          { id: 'wasm-metadata', title: 'How Project Binding Works' },
          { id: 'project-env-vars', title: 'Project Environment Variables' },
          { id: 'storage-security', title: 'Storage Security Model' },
          { id: 'managing-versions', title: 'Managing Versions' },
          { id: 'persistent-storage', title: 'Persistent Storage' },
          { id: 'project-secrets', title: 'Project Secrets' },
          { id: 'use-cases', title: 'Use Cases' },
          { id: 'best-practices', title: 'Best Practices' },
        ],
      },
      {
        href: '/docs/storage',
        label: 'Storage',
        sections: [
          { id: 'overview', title: 'Overview' },
          { id: 'quick-start', title: 'Quick Start' },
          { id: 'api', title: 'Storage API' },
          { id: 'methods', title: 'Methods Reference' },
          { id: 'atomic-operations', title: 'Atomic Operations' },
          { id: 'user-isolation', title: 'User Data Isolation' },
          { id: 'worker-storage', title: 'Worker Storage' },
          { id: 'public-storage', title: 'Public Storage' },
          { id: 'public-http-api', title: 'External HTTP API' },
          { id: 'security', title: 'Security' },
          { id: 'use-cases', title: 'Use Cases' },
          { id: 'best-practices', title: 'Best Practices' },
        ],
      },
      {
        href: '/docs/vrf',
        label: 'VRF (Randomness)',
        sections: [
          { id: 'overview', title: 'Overview' },
          { id: 'how-it-works', title: 'How It Works' },
          { id: 'sdk-usage', title: 'SDK Usage' },
          { id: 'on-chain-verification', title: 'On-Chain Verification' },
          { id: 'security', title: 'Security Properties' },
          { id: 'user-verification', title: 'User Verification Guide' },
          { id: 'api-reference', title: 'API Reference' },
        ],
      },
      {
        href: '/docs/sdk',
        label: 'SDK',
        sections: [
          { id: 'installation', title: 'Installation' },
          { id: 'when-to-use', title: 'When Do You Need the SDK?' },
          { id: 'env-module', title: 'Environment Module' },
          { id: 'storage-module', title: 'Storage Module' },
          { id: 'examples', title: 'Examples Using the SDK' },
          { id: 'minimal-project', title: 'Minimal Project Template' },
          { id: 'api-reference', title: 'API Reference' },
          { id: 'storage-types', title: 'Storage Types Overview' },
        ],
      },
      {
        href: '/docs/https-api',
        label: 'HTTPS API',
        sections: [
          { id: 'overview', title: 'Overview' },
          { id: 'request-format', title: 'Request Format' },
          { id: 'base-urls', title: 'Base URLs (Networks)' },
          { id: 'headers', title: 'Request Headers' },
          { id: 'body', title: 'Request Body' },
          { id: 'response-format', title: 'Response Format' },
          { id: 'env-vars', title: 'Environment Variables' },
          { id: 'errors', title: 'Error Codes' },
          { id: 'examples', title: 'Code Examples' },
        ],
      },
      {
        href: '/docs/payment-keys',
        label: 'Payment Keys',
        sections: [
          { id: 'what-are-payment-keys', title: 'What are Payment Keys?' },
          { id: 'key-format', title: 'Key Format' },
          { id: 'creating-keys', title: 'Creating Payment Keys' },
          { id: 'restrictions', title: 'Key Restrictions' },
          { id: 'balance', title: 'Balance Management' },
          { id: 'rate-limits', title: 'Rate Limits' },
          { id: 'security', title: 'Security Best Practices' },
        ],
      },
      {
        href: '/docs/earnings',
        label: 'Earnings',
        sections: [
          { id: 'how-it-works', title: 'How Earnings Work' },
          { id: 'checking-payment', title: 'Checking Payment in WASM' },
          { id: 'viewing-earnings', title: 'Viewing Your Earnings' },
          { id: 'withdrawing', title: 'Withdrawing Earnings' },
          { id: 'pricing-strategies', title: 'Pricing Strategies' },
          { id: 'best-practices', title: 'Best Practices' },
        ],
      },
      {
        href: '/docs/tee-attestation',
        label: 'TEE Attestation',
        sections: [
          { id: 'what-is-tee', title: 'What is TEE Attestation?' },
          { id: 'worker-registration', title: 'Worker Registration' },
          { id: 'post-quantum-keys', title: 'Post-Quantum Keys' },
          { id: 'execution-attestation', title: 'Execution Attestation' },
          { id: 'trust-model', title: 'What the Signature Proves' },
          { id: 'data-freshness', title: 'Data Freshness' },
          { id: 'verification-process', title: 'Verification Process' },
          { id: 'security-guarantees', title: 'Security Guarantees' },
          { id: 'dashboard-verification', title: 'Dashboard Verification' },
        ],
      },
      {
        href: '/docs/trust-verification',
        label: 'Trust & Verification',
        sections: [
          { id: 'overview', title: 'Trust Architecture' },
          { id: 'deployment-methods', title: 'Two Ways Workers Run' },
          { id: 'verify-deployments', title: 'Verifying Each Deployment' },
          { id: 'verify-execution', title: 'Verify Any Execution' },
          { id: 'outlayer-verify', title: 'OutLayer Verify: Independent Proof' },
          { id: 'measurements', title: '5-Measurement TDX Verification' },
          { id: 'sigstore', title: 'GitHub Releases & Sigstore' },
          { id: 'registration-flow', title: 'Worker Registration Flow' },
          { id: 'ephemeral-keys', title: 'Ephemeral Keys & Blockchain Trail' },
          { id: 'ckd', title: 'Deterministic Keystore Secrets (CKD)' },
          { id: 'operator-limits', title: 'What Operator Cannot Do' },
        ],
      },
      {
        href: '/docs/pricing',
        label: 'Pricing & Limits',
        sections: [
          { id: 'dynamic-pricing', title: 'Dynamic Pricing Model' },
          { id: 'cost-calculation', title: 'Cost Calculation' },
          { id: 'resource-limits', title: 'Resource Limits' },
          { id: 'refund-policy', title: 'Refund Policy' },
          { id: 'optimization-tips', title: 'Optimization Tips' },
        ],
      },
    ],
  },
];
