// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Building a Connector",
  description: "The author side of a connector: the curated namespace and connector_id manifest that make one, the required top-level operation and its fail-closed pricing…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
