// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Connectors",
  description: "What a connector is for the owner who connects an account, the agent that calls it and the enclave that runs it; how a call works, with the diagram; the…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
