// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Example Projects",
  description: "Runnable example agents: verifiable randomness, price and weather oracles, AI inference, NEAR Intents swaps, private DAO voting, 2FA, Telegram bot, on-chain…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
