// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "SDK",
  description: "The Rust `outlayer` crate: environment module, storage module, minimal project template, API reference",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
