// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Settings",
  description: "Your account, network selection and API keys.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
