// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { default: "Execution attestation", template: '%s · OutLayer' },
  description: "Cryptographic proof of an OutLayer execution: enclave signature, TDX measurements and the inputs and outputs of the job.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
