// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Pricing & Limits",
  description: "Dynamic pricing model, cost calculation, resource limits, refund policy",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
