// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Payment Keys",
  description: "Creating payment keys, key format, restrictions, balance management, rate limits, security practices",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
