// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Tutorial: First App",
  description: "End-to-end path: write WASI code, push to GitHub, test on testnet, integrate from a contract",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
