// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Agent Connect (leases)",
  description: "The House of Stake lease mode: an account a partner provisions and lends to an agent under an on-chain spend grant, how that grant is a second ceiling above…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
