// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Tasks",
  description: "Tasks between an agent and its owner: an agent run leaves the owner of a secret row an action to confirm or an input to supply, the owner reads it in the…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
