// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Wallets",
  description: "Policy-guarded agent wallets: freeze or unfreeze keys, manage policies and browser-saved API keys for wallets you control.",
  robots: { index: true, follow: true },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
