// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Trust & Verification",
  description: "Verifying the whole stack: five-measurement Intel TDX verification, Sigstore-signed release images, ephemeral keys and their on-chain trail, deterministic…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
