// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Web2 Integration",
  description: "Using OutLayer from an ordinary backend over HTTPS: quick start, monetization, environment variables, attestation, project capabilities",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
