// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "VRF (Randomness)",
  description: "Verifiable randomness: SDK usage, on-chain proof verification, security properties, user-side verification",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
