// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Payment keys",
  description: "Prepaid USDC keys for the HTTPS API: create keys, top up balances and control spending limits.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
