// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Executions",
  description: "Every compilation and execution job with status, cost and TEE attestation — open any job to verify what exactly ran.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
