// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Earnings",
  description: "What your projects earned from on-chain and HTTPS calls, with balances and withdrawals in one place.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
