// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Personal Account Binding",
  description: "Letting an agent act as a named account its owner already has: the one transaction the holder signs (the wallet contract installed by hash as a global…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
