'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Command } from 'cmdk';
import { APP_NAV, FOOTER_NAV } from '@/lib/nav';
import { DOCS_NAV } from '@/lib/docs-nav.mjs';

interface CommandPaletteProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

/** One section of a docs page in the build-time index (public/search-index.json). */
interface ContentEntry {
  href: string;
  page: string;
  id: string;
  title: string;
  text: string;
}

interface ContentHit extends ContentEntry {
  snippet: string;
  score: number;
}

// The index is generated by scripts/build-search-index.mjs at build time and
// fetched once per session, on the first query long enough to search content.
let indexCache: ContentEntry[] | null = null;
let indexPromise: Promise<ContentEntry[]> | null = null;
function loadIndex(): Promise<ContentEntry[]> {
  if (indexCache) return Promise.resolve(indexCache);
  if (!indexPromise) {
    indexPromise = fetch('/search-index.json')
      .then((r) => (r.ok ? r.json() : []))
      .catch(() => [])
      .then((data: ContentEntry[]) => {
        indexCache = data;
        return data;
      });
  }
  return indexPromise;
}

function searchContent(index: ContentEntry[], query: string): ContentHit[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (words.length === 0) return [];
  const hits: ContentHit[] = [];
  for (const e of index) {
    const title = e.title.toLowerCase();
    const page = e.page.toLowerCase();
    const text = e.text.toLowerCase();
    let score = 0;
    let ok = true;
    for (const w of words) {
      if (title.includes(w)) score += 5;
      else if (page.includes(w)) score += 3;
      const n = text.split(w).length - 1;
      if (n > 0) score += Math.min(n, 5);
      else if (!title.includes(w) && !page.includes(w)) {
        ok = false;
        break;
      }
    }
    if (!ok || score === 0) continue;
    const i = text.indexOf(words[0]);
    const start = Math.max(0, i - 40);
    const end = Math.min(e.text.length, i + words[0].length + 70);
    const snippet =
      (start > 0 ? '…' : '') + e.text.slice(start, end).trim() + (end < e.text.length ? '…' : '');
    hits.push({ ...e, snippet, score });
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, 8);
}

const ITEM_CLS =
  'cursor-pointer rounded-md px-3 py-2 text-sm text-foreground aria-selected:bg-accent/10 aria-selected:text-accent-text';
const GROUP_CLS =
  '[&_[cmdk-group-heading]]:px-3 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-[10px] [&_[cmdk-group-heading]]:font-semibold [&_[cmdk-group-heading]]:uppercase [&_[cmdk-group-heading]]:tracking-wider [&_[cmdk-group-heading]]:text-faint-foreground';

export default function CommandPalette({ open, onOpenChange }: CommandPaletteProps) {
  const router = useRouter();
  const [query, setQuery] = useState('');
  const [contentHits, setContentHits] = useState<ContentHit[]>([]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'k' && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        onOpenChange(!open);
      }
      if (e.key === 'Escape' && open) onOpenChange(false);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, onOpenChange]);

  // Full-text lookup for queries of 3+ chars; result discarded if the query
  // moved on while the index was still loading.
  useEffect(() => {
    const q = query.trim();
    if (q.length < 3) {
      setContentHits([]);
      return;
    }
    let stale = false;
    loadIndex().then((index) => {
      if (!stale) setContentHits(searchContent(index, q));
    });
    return () => {
      stale = true;
    };
  }, [query]);

  useEffect(() => {
    if (!open) {
      setQuery('');
      setContentHits([]);
    }
  }, [open]);

  if (!open) return null;

  const go = (href: string) => {
    onOpenChange(false);
    router.push(href);
  };

  const q = query.trim().toLowerCase();
  const matches = (label: string) => !q || label.toLowerCase().includes(q);

  const navGroups = [...APP_NAV, { group: 'General', items: FOOTER_NAV }]
    .map((group) => ({
      heading: group.group ?? 'App',
      items: group.items.filter((item) => matches(item.label)),
    }))
    .filter((g) => g.items.length > 0);

  const docsPages = DOCS_NAV.flatMap((g) => g.pages).filter((page) => matches(page.label));
  const docsSections = DOCS_NAV.flatMap((g) => g.pages).flatMap((page) =>
    page.sections
      .filter((section) => matches(`${page.label} ${section.title}`))
      .map((section) => ({ page, section })),
  );

  // Content hits that duplicate an already-listed heading match add noise.
  const shownAnchors = new Set(docsSections.map(({ page, section }) => `${page.href}#${section.id}`));
  const uniqueHits = contentHits.filter((h) => !shownAnchors.has(`${h.href}#${h.id}`));

  return (
    <div
      className="fixed inset-0 z-[100] flex items-start justify-center bg-black/40 pt-[12vh]"
      onClick={() => onOpenChange(false)}
    >
      <div className="w-full max-w-lg px-4" onClick={(e) => e.stopPropagation()}>
        <Command
          label="Command palette"
          shouldFilter={false}
          className="overflow-hidden rounded-xl border border-border-strong bg-card shadow-2xl"
        >
          <Command.Input
            autoFocus
            value={query}
            onValueChange={setQuery}
            placeholder="Search pages and docs…"
            className="w-full border-b border-border bg-transparent px-4 py-3 text-sm text-foreground outline-none placeholder:text-faint-foreground"
          />
          <Command.List className="max-h-[50vh] overflow-y-auto p-2">
            <Command.Empty className="px-3 py-6 text-center text-sm text-muted-foreground">
              Nothing found.
            </Command.Empty>

            {navGroups.map((group) => (
              <Command.Group key={group.heading} heading={group.heading} className={GROUP_CLS}>
                {group.items.map((item) => (
                  <Command.Item
                    key={item.href}
                    value={`nav:${item.href}`}
                    onSelect={() => go(item.href)}
                    className={ITEM_CLS}
                  >
                    {item.label}
                  </Command.Item>
                ))}
              </Command.Group>
            ))}

            {(docsPages.length > 0 || docsSections.length > 0) && (
              <Command.Group heading="Docs" className={GROUP_CLS}>
                {docsPages.map((page) => (
                  <Command.Item
                    key={page.href}
                    value={`docs:${page.href}`}
                    onSelect={() => go(page.href)}
                    className={ITEM_CLS}
                  >
                    {page.label}
                    <span className="ml-2 text-xs text-faint-foreground">docs</span>
                  </Command.Item>
                ))}
                {docsSections.map(({ page, section }) => (
                  <Command.Item
                    key={`${page.href}#${section.id}`}
                    value={`docs:${page.href}#${section.id}`}
                    onSelect={() => go(`${page.href}#${section.id}`)}
                    className={ITEM_CLS}
                  >
                    <span className="text-faint-foreground">{page.label}&nbsp;›&nbsp;</span>
                    {section.title}
                  </Command.Item>
                ))}
              </Command.Group>
            )}

            {uniqueHits.length > 0 && (
              <Command.Group heading="Docs content" className={GROUP_CLS}>
                {uniqueHits.map((hit) => (
                  <Command.Item
                    key={`content:${hit.href}#${hit.id}`}
                    value={`content:${hit.href}#${hit.id}`}
                    onSelect={() =>
                      // ?q= lets the docs page highlight the matches (SearchHighlighter).
                      go(
                        `${hit.href}?q=${encodeURIComponent(query.trim())}${hit.id ? `#${hit.id}` : ''}`,
                      )
                    }
                    className={`${ITEM_CLS} flex flex-col items-start gap-0.5`}
                  >
                    <span>
                      <span className="text-faint-foreground">{hit.page}&nbsp;›&nbsp;</span>
                      {hit.title}
                    </span>
                    <span className="line-clamp-1 text-xs text-muted-foreground">{hit.snippet}</span>
                  </Command.Item>
                ))}
              </Command.Group>
            )}
          </Command.List>
        </Command>
      </div>
    </div>
  );
}
