// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Signing Keys",
  description: "ed25519 keys a WASI module signs with and never sees, derived in the TEE keystore per project or exact build and per caller: the manifest signing_keys…",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
