// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Storage",
  description: "Persistent key-value storage for agents: methods reference, atomic operations, per-user isolation, public storage and its external HTTP read API",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
