// @generated by scripts/gen-seo-layouts.mjs — edit the generator, not this file.
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Payment Checks",
  description: "Gasless agent-to-agent payments: transfer mechanism, key derivation, check lifecycle, security model",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
